-- V1: ベースラインスキーマ
--
-- ここまでは Hibernate の ddl-auto=update がスキーマを作っていた。以降は Flyway が正。
--
-- ⚠️ 既存DB（本番VM・ローカルの lab-db-1）には spring.flyway.baseline-on-migrate=true と
--    baseline-version=1 が効くため、このV1は **実行されず** 「適用済み」として記録される。
--    実際に走るのは空DB（テストのH2・新規環境）だけ。
--    内容は pg_dump した実物から起こしてあるが、**実DBが間違っていた箇所は正しい姿で書いてある**
--    （orders.user_id の NULL 可・status の EXPIRED）。実DB側の是正は V3 が行う。
--
-- CHECK 制約には明示的な名前を付ける。Hibernate 任せの自動生成名だと DB ごとに変わり、
-- 後から ALTER で直せない（実際それで status への EXPIRED 追加が漏れていた）。
--
-- SQL は H2(MODE=PostgreSQL) と PostgreSQL の両方で動く書き方に限定する。
-- テストは H2 で走るので、ここが壊れれば CI が赤くなる＝本番に出る前に気づける。

CREATE TABLE users (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    email      varchar(255) NOT NULL UNIQUE,
    name       varchar(255) NOT NULL,
    password   varchar(255) NOT NULL,
    role       varchar(255) NOT NULL,
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE categories (
    id   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL UNIQUE
);

CREATE TABLE products (
    id           bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   timestamp(6) with time zone NOT NULL,
    name         varchar(255)  NOT NULL,
    description  varchar(2000),
    image_url    varchar(255),
    price        numeric(12,2) NOT NULL,
    -- stock=実在庫、reserved=引当済み。販売可能数は stock - reserved。
    stock        integer       NOT NULL,
    reserved     integer       NOT NULL DEFAULT 0,
    tax_category varchar(255)  NOT NULL DEFAULT 'STANDARD',
    category_id  bigint        REFERENCES categories (id),
    CONSTRAINT ck_products_tax_category CHECK (tax_category IN ('STANDARD', 'REDUCED'))
);

CREATE TABLE cart_items (
    id         bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   integer NOT NULL,
    user_id    bigint  NOT NULL REFERENCES users (id),
    product_id bigint  NOT NULL REFERENCES products (id),
    UNIQUE (user_id, product_id)
);

CREATE TABLE orders (
    id                bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        timestamp(6) with time zone NOT NULL,
    -- ログイン購入なら購入者。**ゲスト購入では NULL**（guest_email + order_token で識別する）。
    user_id           bigint        REFERENCES users (id),
    guest_email       varchar(255),
    -- ゲスト注文の照会トークン。発行時に一度だけ返す。
    order_token       varchar(255)  UNIQUE,
    status            varchar(255)  NOT NULL,
    -- 注文時点の税設定・金額は凍結する（後から税率が変わっても過去注文は動かない）。
    pricing_mode      varchar(255)  NOT NULL,
    subtotal_amount   numeric(12,2) NOT NULL,
    tax_amount        numeric(12,2) NOT NULL,
    total_amount      numeric(12,2) NOT NULL,
    -- 決済手段に依存しない参照。Stripe なら checkout session id が入る。
    payment_provider  varchar(255),
    payment_reference varchar(255),
    stripe_session_id varchar(255),
    CONSTRAINT ck_orders_status CHECK (
        status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT ck_orders_pricing_mode CHECK (pricing_mode IN ('INCLUSIVE', 'EXCLUSIVE'))
);

CREATE TABLE order_items (
    id               bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         bigint        NOT NULL REFERENCES orders (id),
    product_id       bigint        NOT NULL REFERENCES products (id),
    -- 商品名・単価も注文時のスナップショット（後で商品が改名・値上げされても伝票は不変）。
    product_name     varchar(255)  NOT NULL,
    quantity         integer       NOT NULL,
    unit_price       numeric(12,2) NOT NULL,
    tax_category     varchar(255)  NOT NULL,
    tax_rate_percent numeric(5,2)  NOT NULL,
    tax_amount       numeric(12,2) NOT NULL,
    CONSTRAINT ck_order_items_tax_category CHECK (tax_category IN ('STANDARD', 'REDUCED'))
);

CREATE TABLE tax_rates (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       varchar(255) NOT NULL,
    rate_percent   numeric(5,2) NOT NULL,
    -- 有効期間つき。effective_to が NULL なら現行。
    effective_from date         NOT NULL,
    effective_to   date,
    CONSTRAINT ck_tax_rates_category CHECK (category IN ('STANDARD', 'REDUCED'))
);

CREATE TABLE app_settings (
    setting_key   varchar(64)  PRIMARY KEY,
    setting_value varchar(255) NOT NULL
);
